[package]
name = "virtmgr-test-disk"
version = "0.0.0"
edition = "2021"

[dependencies]
disk = { path = "../../../../../external/crosvm/disk", default-features = false, features = ["composite-disk"] }
