[package]
name = "android_hardware_security_secretkeeper"
version = "0.1.0"
edition = "2021"
description = "Rust bindings for Android Hardware Security Secretkeeper AIDL interfaces"
license = "Apache-2.0"

[lib]
name = "android_hardware_security_secretkeeper"
path = "android_hardware_security_secretkeeper.rs"

[dependencies]
binder = { path = "../../../../../../../../../../frameworks/native/libs/binder/rust" }
android_hardware_security_authgraph = { path = "../authgraph" }
async-trait = "0.1.74"

[features]
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    "cfg(android_vendor)",
    "cfg(android_ndk)",
    "cfg(android_vndk)",
    "cfg(trusty)",
] }

[profile.release]
lto = true
opt-level = "z"
